### ISSUE TITLE
potager

### ISSUE THREAD

**Issue by amoi69** [frixo3190/jeedom_plugins#1]
Bonjour,

Après installation du plugin, j'ai un problème avec les URL 'planning' et 'gérer mes potager'.
En effet ma root URL est
http://192.168.69.2/jeedom/index.php?v=d&m=potager&p=potager
 ce qui fonctionne correctement car dans la configuration de Jeedom j'ai renseigné les information 'réseaux' interne et externe.

Par contre pour 'planning' et 'gérer mes potager' lorsque je clique l'URL est 
http://192.168.69.2/index.php?v=d&m=potager&p=panel
avec une page not found car il manque dans l'URL le repertoire "jeedom" dans l'arborescence.
Si je modifie à la main l'URL en 
http://192.168.69.2/jeedom/index.php?v=d&m=potager&p=panel
cela fonctionne.

Pouvez-vous donc prendre en le chemin de base rentrer dans la configuration 'réseau' de Jeeedom?

Merci

**Comment by frixo3190** [comment]
Bonjour,

j'ai publié un correctif sur la Beta

pourrais tu s'il te plait le valider ,

il faudrait entre autre me confirmer que :
- la recherche d'une semence fonctionne (en mode potager et planning) stp.

vu que j'ai pas ce paramètre , ni en VM ni en prod, j'ai un peu dev a
l'aveugle

dans l'attente de ton retour ?


sais tu installer une beta ?

cdt

**Comment by amoi69** [comment]
Bonjour,

je vois d'autre plugins en Beta ainsi que que le core mais pas potager.
et sur Market, il ne m'est prposé que la stable.

Merci pour votre aide

**Comment by amoi69** [comment]
Désolé, j'avais dû faire une fausse manip, j'ai la beta maintenant.

Je teste

**Comment by frixo3190** [comment]
Super

**Comment by amoi69** [comment]
Désolé, j'ai toujours le soucis d'URL avec mon dossier 'jeedom' manquant.

La recherche de semence ne donne rien non plus puisque après avoir corrigé à la main l'URL, j'ai accès au mode potager 
http://192.168.69.2/jeedom/index.php?v=d&m=potager&p=panel

mais lorsque je clique sur planning, une fenêtre vide s'affiche avec un pop up d'erreur jeedom 'page non trouvée'

![pot1](https://user-images.githubusercontent.com/68010701/113749147-98dc3400-9709-11eb-8806-737c5ab35ed8.png)
![pot2](https://user-images.githubusercontent.com/68010701/113749161-9da0e800-9709-11eb-9716-4ecc967c1b93.png)
![pot3](https://user-images.githubusercontent.com/68010701/113749170-a1cd0580-9709-11eb-9c53-ae74ba8dd1b1.png)

je te joins des capture d'écrans si cela peut être utile.

merci

**Comment by amoi69** [comment]
![pot4](https://user-images.githubusercontent.com/68010701/113749827-60892580-970a-11eb-97fe-900f83c6cae5.png)
et voici le settings dans jeedom dont je te parlais avec le repertoire de base de jeedom dans les accès interne et externe.

**Comment by frixo3190** [comment]
salut


fait la maj beta (la nouvelle, tu force la recherche de maj jeedom) , et va
sur

/index.php?v=d&m=potager&p=debug (rajoute /jeedom/ devant du coup toi)

et envoi moi le résultat stp

merci

**Comment by amoi69** [comment]
voici le résultat:
DEBUG
internalAddr : hiden
internalComplement : jeedom
externalAddr : hiden.noip.me
externalComplement : jeedom
mode : inconnu
base_url :

bon courage et merci

**Comment by frixo3190** [comment]
Bein

Pourquoi ya marqué hiden ?

Moi j'ai mon ip

C'est toi qui a remplacé ?

Tu as quoi dans ta page de conf de jeedom ? Tu as hiden aussi ?

Cdt

**Comment by amoi69** [comment]
Bonjour,

Je ne me souviens pas avoir remplacé mais comme j'ai mon propre DNS, la conversion a peut être été faite toute seule.
En plus cette notion et interne/externe est assez ressente, je crois qu'elle est arrivée avec la V3 de mémoire (j'ai jeedom depuis très très très longtemps ;-) )

Oui dans ma page de conf j'ai hiden aussi, mais celafonctionne très bien comme cela.

Cordialement,

**Comment by frixo3190** [comment]
Comment veux tu que je devienne si tu es en interne ou externe si je peux
pas comparer ton URL de base avec la conf

Je peux pas deviner quel base rajouter  ( le complément interne ou externe
, dans ton cas c'est le même mais il pourrait être différent)

Peux tu stp mettre ton ip local en interne et retenter la page debug ainsi
que le plugin potager stp

Cdt

**Comment by amoi69** [comment]
je vais changer ma conf mais a priori le complément doit être le même, à moins d'avoir une configuration tirée par les cheveux puisque, le répertoire d'installation de jeedom est le même que tu y accèdes depuis ton réseau interne ou depuis l'exterieur. Et si il y avait un besoin pour qu'il soit différent il est plus simple de jouer avec la configuration de apache ou autre serveur web que de se casser la tête à gérer un double repertoire d'installation.
Je te mets les résultats de debug dans mon prochain message.

**Comment by amoi69** [comment]
voici le debug:

DEBUG
internalAddr : 192.168.69.2
internalComplement : jeedom
externalAddr : hiden.noip.me
externalComplement : jeedom
mode : interne
base_url : jeedom

**Comment by frixo3190** [comment]
Salut

Alors , le 'a priori' on oublie
S'il y a 2 champs de conf, je programme proprement pour prendre en compte
les 2

Et regarder la conf Apache , ça devient usine à gaz 😀

J'attends ton retour

Merci

**Comment by amoi69** [comment]
Tu as le résultat du debug ci-dessus, et pour le plugin j'ai maintenant le complement qui apparait dan les URL donc j'ai 2 fois 'jeedom'
![pot5](https://user-images.githubusercontent.com/68010701/113828670-f5306980-9784-11eb-9a6a-70e5fb930b60.png)
![pot6](https://user-images.githubusercontent.com/68010701/113828690-f95c8700-9784-11eb-8577-e5e3ee651b3a.png)

Merci

**Comment by frixo3190** [comment]
Ok

tu peux refaire une maj et retenter stp ?

**Comment by amoi69** [comment]
Le plugin fonctionne correctment avec la dernière beta sur planning et gérer mon potager.
Un grand merci pour ton aide!
Dis moi si je peux clore l'issue?

Bonne journée

**Comment by frixo3190** [comment]
super !

check bien stp la recherche de semence via le potager et via le planning, et test bien tout, je suis pas sur d'avoir mis a jour toutes les url

j'attend ton dernier retour pour clore l'issue et publier en stable

ravi de t'avoir aidé

**Comment by amoi69** [comment]
La recherche de semences fonctionne, par contre je pense que des icones me manque sur planning par exemple:
![pot7](https://user-images.githubusercontent.com/68010701/113837098-cbc80b80-978d-11eb-8073-d07de1d5f51c.png)
en début de ligne de tomates je n'ai pas les icones,

et sur gestion:
![pot8](https://user-images.githubusercontent.com/68010701/113837215-e69a8000-978d-11eb-92da-049e84270799.png)
il doit me manquer dalles, arbres, composteur, cuve et abris.

**Comment by frixo3190** [comment]
OK

refait une maj et dis moi si c'est mieu

**Comment by amoi69** [comment]
C'est bon pour les icone de planning.
Mais il me manque les couleurs associées à quelques éléments du jardin (abris, dalles, arbres, cuve, composteurs):
![pot9](https://user-images.githubusercontent.com/68010701/113840106-a12b8200-9790-11eb-9833-c7f2f11f0377.png)

**Comment by frixo3190** [comment]
Je pense que tu as un problème de cache réessaye en navigation privée s'il
te plaît

**Comment by amoi69** [comment]
Je n'ai pas mieux en navigation privée ni après un shift reload:
![pot10](https://user-images.githubusercontent.com/68010701/113841325-e00e0780-9791-11eb-96cb-4a75e20cb75e.png)

**Comment by frixo3190** [comment]
ok, refait la maj et dis moi stp

**Comment by amoi69** [comment]
j'ai retrouvé les éléments manquants, super.
Un dernier point, le menu contextuel clique droit n'est pas affiché correctement:
![pot11](https://user-images.githubusercontent.com/68010701/113855745-adb7d680-97a0-11eb-90f7-fb69fe705594.png)
quelque soit la position de l'élément sur l'écran (à gauche, à droite, au centre), le menu s'affiche toujours sur le bord gauche de manière incomplète

**Comment by frixo3190** [comment]
Ton potager est trop petit
Étire le  ( le terrain marron)

**Comment by amoi69** [comment]
oppps erreur de débutant ;-)
Bon je crois que tout est ok maintenant.

Un très grand merci pour ton aide et ta disponibilité!

PS: pour une future version il serait bien de pouvoir choisir le jour du semis, car si je mets à jour l'état du semis, c'est la date du jour qui est prise, alors que j'ai fait mes semis sous abris mi Mars.

Bon courage à toi et vu le travail que tu as fourni, 4 euros ce n'est vraiment pas cher...

**Comment by frixo3190** [comment]
À toi il faut que tu lises la doc🤣

On peut customiser la date en mode planning en appuyant sur contrôle en
même temps que cliquez

Désolé je dicte au téléphone ça écrit un peu n'importe quoi

**Comment by amoi69** [comment]
Super, merci pour tout et si tu as besoin d'un beta testeur ...

Bonne journée
