### ISSUE TITLE
nouvelle version

### ISSUE THREAD

**Issue by amoi69** [frixo3190/jeedom_plugins#2]
Bonjour,
c'est encore moi, l'empêcheur de jardiner en rond.

Avec la nouvelle version V2 des semis (bravo pour cette nouveauté), j'ai de nouveau le soucis des images qui ne s'affichent pas. Dans mon URL il n'est pas pris en compte la configuration réseau de Jeedom (le repertoire root de l'installation de mon Jeedom).
Pour être très précis ce sont les nouvelles images (tomates, concombres, salades...) qui ne s'affichent pas. Les anciennes (graines et germées et mis en terre) sont ok.

Idem lorsque je suis sur planning et que je fais un clic droit -> 'accèder à la fiche semance', j'ai le même problème d'url incorrecte avec le manque de mon répertoire root.

Si tu as besoin de plus de détails, dit le moi je te ferais des copies d'écrans.

Merci pour ton aide et ce plugin qui deviens exceptionnel.

**Comment by frixo3190** [comment]
salut

dsl j'avais zappé, j'ai posté une maj en Beta pour toi

cdt

**Comment by amoi69** [comment]
Merci,

c'est ok pour la vue potager. 
Par contre ce n'est pas bon pour la vue gestion, ni pour la fiche semence à partir de la vue planning.

cdlt

**Comment by frixo3190** [comment]
refait une maj et dis moi stp

**Comment by amoi69** [comment]
C'est bon pour la vue gestion, il ne reste plus qu'à solutionner l'accès à la fiche semence sur clic droit dans la vue planning.

Merci pour ton support

**Comment by frixo3190** [comment]
Quelle vue ?

Tu me fais un screenshot ?

**Comment by amoi69** [comment]
la vue planning:
![image](https://user-images.githubusercontent.com/68010701/118869171-5b142300-b8e5-11eb-9936-818d733fb211.png)
![image](https://user-images.githubusercontent.com/68010701/118869209-66ffe500-b8e5-11eb-8392-cda263110749.png)

**Comment by frixo3190** [comment]
Ah ok

Refait la maj et dis moi !

**Comment by amoi69** [comment]
Bonjour,
désolé je n'ai pas été disponible hier soir.

J'ai refait la mise à jour, mais il manque un "/" dans l'url, je t'ai fait une copie d'écran:
![image](https://user-images.githubusercontent.com/68010701/119014640-768c3600-b998-11eb-9a67-191ed2eeb808.png)

**Comment by frixo3190** [comment]
c'est corrigé

**Comment by amoi69** [comment]
C'est bon fonctionne.
Un grand merci encore pour ton support et aussi le plugin qui est vraiment génial.

Bonne soirée

**Comment by frixo3190** [comment]
Top
