### ISSUE TITLE
Problème cron arrosage 

### ISSUE THREAD

**Issue by theobeaudenon** [frixo3190/jeedom_plugins#3]
Quand je met ce cron ; */40 * * * *

https://i.ibb.co/1sWRRB2/Screenshot-20210610-230938.jpg

Cela devrait être toutes les 45 minutes

**Comment by frixo3190** [comment]
Bonjour

J'utilise la fonction fourni par jeedom
Je n'ai rien développé moi même à ce sujet
Je suis désolé
Peut être qu'un screenshots du moteur de Cron jeedom aiderait

Cdt

Le jeu. 10 juin 2021 à 23:15, theobeaudenon ***@***.***> a
écrit :

**Comment by frixo3190** [comment]
![image](https://user-images.githubusercontent.com/23532434/121645816-ea4fc900-ca94-11eb-995d-9981d340ce06.png)

![image](https://user-images.githubusercontent.com/23532434/121645894-02bfe380-ca95-11eb-93c7-e8996b1a5d2b.png)

**Comment by frixo3190** [comment]
je viens de faire un test
un cron toutes les 2 min
un timer de off de 1min
j'ai bien mon virtuel qui s'allume 1min puis s'éteint

**Comment by frixo3190** [comment]
je t'invite a :
- vérifier que tu as bien la dernière maj Potager Stable
- basculer en log debug pour plus d'analyse
- bien vérifier tes conditions d'arrosages

**Comment by theobeaudenon** [comment]
Je viens de regarder les expression cron 
*/40 * * * * = toutes les 45 minutes, à partir de la minute 0 de chaque heure, du coup mon problème est normal. 

Pour faire ce que je veux il faut que je créer 3 cron 

0 0/45 12/3 * * ?    # 12:00, 12:45, 15:00, 15:45, ...
0 30 13/3 * * ?      # 13:30, 16:30, ...
0 15 14/3 * * ?
