### ISSUE TITLE
Gain estimé journalier en ETH

### ISSUE THREAD

**Issue by nufissime** [frixo3190/jeedom_plugins#4]
Bonjour,

Serait-il possible d'avoir dans le plugin Jeedom Ethermine la valeur "Estimated Earnings" en ETH de la page dashboard d'Ethermine ?

Cette valeur est disponible en euros, mais elle m'intéresse plus en ETH pour pouvoir suivre l'évolution de la quantité minée au cours du temps.

Merci

**Comment by frixo3190** [comment]
Bonjour, 
c'est rajouté dans la maj
pense a re-enregistrer ton équipement pour que les 3 nouvelles commandes soient crées 

Pour ces 3 commande en ETH je ne déduit pas la conso elec, alors que si tu as déclarée la puissance instantanée de ton ring, dans l'estimation en euro , je déduit la conso elec réel.

cdt

**Comment by nufissime** [comment]
Merci pour la maj !

Les valeurs dans jeedom sont différentes de celles affichées dans la console Ethermine, c'est normal ?

**Comment by frixo3190** [comment]
C'est des estimations calculé
Je ne prend pas les valeurs de ethermine
En gros il y a un Cron toute les 5 min qui regarde CB on mine et ça
extrapole , plus le temps passe plus l'extrapolation s'affine jusqu'au
versement où tout se remet à 0

Le mar. 29 juin 2021 à 11:17, lucasarnulphy ***@***.***> a
écrit :

**Comment by nufissime** [comment]
Super c'est encore mieux ! merci
